### ISSUE TITLE
Refactor `cache_test.go` 

### ISSUE THREAD

**Issue by gozeloglu** [gozeloglu/cache#3]
[`cache_test.go`](https://github.com/gozeloglu/cache/blob/main/cache_test.go) should be refactored to follow Go-style table-driven test. 

## Why was it written like that?

I was a newbie in Go while I was implementing this package.

## Why is it important?

* In the current version, test files are not maintainable and readable. It is really hard to make changes or add new test cases. 
* Go has some conventions like writing tests in a table-driven style. It will be better if the test functions are refactored for welcoming new contributors. Go developers are familiar with test style and it makes the project understandable for them.
* It is hard to detect bugs now. 

## TODOs

- [ ] Convert test functions to table-driven tests.
- [ ] Keep test coverage rate.

## Resources

* https://dave.cheney.net/2019/05/07/prefer-table-driven-tests 
* https://go.dev/blog/subtests 
* https://semaphoreci.com/blog/table-driven-unit-tests-go
* https://dev.to/boncheff/table-driven-unit-tests-in-go-407b

**Comment by atifcppprogrammer** [comment]
Merhaba @gozeloglu ! I would like to work on this issue please assign it to me ! Teşekkür ederim :+1:

**Comment by gozeloglu** [comment]
> Merhaba @gozeloglu ! I would like to work on this issue please assign it to me ! Teşekkür ederim 👍

Hi @atifcppprogrammer. You can go ahead. Thank you

**Comment by atifcppprogrammer** [comment]
@gozeloglu, please do review the PR when you have the time. 😊
